version: "3"
services:
  node-bsc-testnet:
    image: graphprotocol/graph-node
    platform: linux/amd64
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8020:8020"
      - "8030:8030"
      - "8040:8040"
    # depends_on:
    #   - ipfs
    #   - postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: "ipfs:5001"
      # ethereum: "bsc-testnet:https://bsc-testnet.public.blastapi.io"
      ethereum: "bsc-testnet:https://restless-frequent-patina.bsc-testnet.quiknode.pro/46b3d0285e3746b08128788bf6cf0f707316042d/"
      GRAPH_LOG: info
      GRAPH_GETH_ETH_CALL_ERRORS: "execution fatal"
    restart: always
    deploy:
      resources:
        limits:
          memory: 8G
