version: "3"
services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "9000:80"
    volumes:
      - ./data/pgadmin:/data/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    depends_on:
      - postgres
    restart: always
  ipfs:
    image: ipfs/go-ipfs:v0.19.1
    platform: linux/amd64
    ports:
      - "5001:5001"
    volumes:
      - ./data/ipfs:/data/ipfs
    restart: always
  postgres:
    image: postgres:15.2
    ports:
      - "5432:5432"
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      # FIXME: remove this env. var. which we shouldn't need. Introduced by
      # <https://github.com/graphprotocol/graph-node/pull/3511>, maybe as a
      # workaround for https://github.com/docker/for-mac/issues/6270?
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
